<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Default5.aspx.cs" Inherits="Default5" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
                <asp:GridView ID="gvEmp" runat="server" AutoGenerateColumns="false" ShowFooter="true" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" OnRowDeleting="gvEmp_RowDeleting" OnRowCancelingEdit="gvEmp_RowCancelingEdit" OnRowEditing="gvEmp_RowEditing" OnRowUpdating="gvEmp_RowUpdating" OnSelectedIndexChanged="gvEmp_SelectedIndexChanged" style="height: 166px; width: 647px">
                <Columns>
                    <asp:TemplateField>
                        <HeaderTemplate>
                            <asp:Label ID="lblid" runat="server" Text="EMP ID" />
                        </HeaderTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblid1" runat="server" Text='<%#Eval("Empid") %>' />
                        </ItemTemplate>
                        <FooterTemplate>
                            <asp:Button ID="btninsert" runat="server" Text="Insert" CommandName="Insert" />
                            <asp:TextBox ID="txtid" runat="server" Text="" />
                        </FooterTemplate>
                        <EditItemTemplate>
                            <asp:TextBox ID="txtid1" runat="server" Text='<%#Eval("Empid") %>' />
                        </EditItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField>
                        <HeaderTemplate>
                            <asp:Label ID="lblname" runat="server" Text="Name" />
                        </HeaderTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblname1" runat="server" Text='<%#Eval("Empname") %>' />
                        </ItemTemplate>
                        <FooterTemplate>
                            <asp:TextBox ID="txtname" runat="server" Text="" />
                        </FooterTemplate>
                         <EditItemTemplate>
                            <asp:TextBox ID="txtname1" runat="server" Text='<%#Eval("Empname") %>' />
                        </EditItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField>
                        <HeaderTemplate>
                            <asp:Label ID="lblcity" runat="server" Text="EMP City" />
                        </HeaderTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblcity1" runat="server" Text='<%#Eval("Empcity") %>' />
                        </ItemTemplate>
                        <FooterTemplate>
                            <asp:TextBox ID="txtcity" runat="server" Text="" />
                        </FooterTemplate>
                         <EditItemTemplate>
                            <asp:TextBox ID="txtcity1" runat="server" Text='<%#Eval("Empcity") %>' />
                        </EditItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField>
                        <HeaderTemplate>
                            <asp:Label ID="lblsalary" runat="server" Text="Salary" />
                        </HeaderTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblsalary1" runat="server" Text='<%#Eval("Empsalary") %>' />
                        </ItemTemplate>
                        <FooterTemplate>
                            <asp:TextBox ID="txtsalary" runat="server" Text="" />
                        </FooterTemplate>
                         <EditItemTemplate>
                            <asp:TextBox ID="txtsalary1" runat="server" Text='<%#Eval("Empsalary") %>' />
                        </EditItemTemplate>
                    </asp:TemplateField>
                </Columns>
            </asp:GridView>
    </div>
    </form>
</body>
</html>
